DROP TABLE IF EXISTS urls CASCADE;

CREATE TABLE urls (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  date_created DATE NOT NULL,
  long_url VARCHAR(255) NOT NULL,
  short_url VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL
);