DROP TABLE IF EXISTS visits CASCADE;

CREATE TABLE visits (
  id SERIAL PRIMARY KEY NOT NULL,
  visitor INTEGER REFERENCES users(id) ON DELETE CASCADE,
  url_id INTEGER REFERENCES urls(id) ON DELETE CASCADE,
  date_visited DATE NOT NULL
);